### ISSUE TITLE
Without Algolia

### ISSUE THREAD

**Issue by emresaracoglu** [MarkNjunge/InstantSearch-Android#1]
Hello,

So good project, thank you. Can I use it as local file JSON without of Algolia? 

Thank you

**Comment by emresaracoglu** [comment]
UPDATE // I trying but I getting this error:

 

> Could not get unknown property 'ALGOLIA_APPLICATION_ID' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=21, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=26, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=com.marknkamau.algoliatest, testApplicationId=null, testInstrumentationRunner=android.support.test.runner.AndroidJUnitRunner, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.
> Open File 

Can't I use this project without the possibility of angolia? :)

**Comment by MarkNjunge** [comment]
Sorry for replying so late. I somehow missed this is my feed.  

This is how it would look:
``` Kotlin
val yourListOfData: List<YourModel> = // Load your data from JSON

RxSearch.fromSearchView(searchView)
    // Set the minimum length searchable
    .filter {
        it.length > 3
    }
    // The amount of time before it starts to search after a user stops typing
    .debounce(300, TimeUnit.MILLISECONDS)
    .map {
        // Use Kotlin's filter method
        yourListOfData.filter { it.title.contains(text, true) }
    }
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(
            { result ->
                pbLoading.visibility = View.GONE
                dataAdapter.setItems(result)
            },
            { throwable ->
                Timber.e(throwable)
                Toast.makeText(this, throwable.message, Toast.LENGTH_SHORT).show()
            })

```
